/* JavaScript file Generated by
 * Creativyst(tm) CSV converter
 *   (www.creativyst.com)
 * 
 * (C) Copyright 2002-2003, Creativyst, Inc.
 * 
 * Permission is hereby granted to use,
 * distribute, and change this file for any
 * reason, provided this entire comment remains
 * intact with the work.
 * 
 *
*/

/*JSCPragma:StartCompress
*/

var lsz = 53;

var Col0 = Array([lsz]);
var Col1 = Array([lsz]);

Col0[0] = "state";
Col1[0] = "income";

Col0[1] = "Washington, D.C.";
Col1[1] = "45004";

Col0[2] = "Connecticut";
Col1[2] = "37807";

Col0[3] = "Maryland";
Col1[3] = "36056";

Col0[4] = "New Jersey";
Col1[4] = "35928";

Col0[5] = "Massachusetts";
Col1[5] = "35485";

Col0[6] = "Virginia";
Col1[6] = "33326";

Col0[7] = "New Hampshire";
Col1[7] = "32758";

Col0[8] = "Alaska";
Col1[8] = "32537";

Col0[9] = "New York";
Col1[9] = "32104";

Col0[10] = "Colorado";
Col1[10] = "31039";

Col0[11] = "Washington";
Col1[11] = "30661";

Col0[12] = "Minnesota";
Col1[12] = "30656";

Col0[13] = "Rhode Island";
Col1[13] = "30005";

Col0[14] = "Delaware";
Col1[14] = "29733";

Col0[15] = "California";
Col1[15] = "29551";

Col0[16] = "Illinois";
Col1[16] = "29519";

Col0[17] = "Hawaii";
Col1[17] = "29227";

Col0[18] = "Wyoming";
Col1[18] = "28858";

Col0[19] = "Vermont";
Col1[19] = "28846";

Col0[20] = "North Dakota";
Col1[20] = "28700";

Col0[21] = "Pennsylvania";
Col1[21] = "28190";

Col0[22] = "United States";
Col1[22] = "28051";

Col0[23] = "Wisconsin";
Col1[23] = "27426";

Col0[24] = "Nevada";
Col1[24] = "27003";

Col0[25] = "Kansas";
Col1[25] = "26845";

Col0[26] = "Oregon";
Col1[26] = "26702";

Col0[27] = "Iowa";
Col1[27] = "26545";

Col0[28] = "Nebraska";
Col1[28] = "26523";

Col0[29] = "Maine";
Col1[29] = "26464";

Col0[30] = "Florida";
Col1[30] = "26451";

Col0[31] = "Ohio";
Col1[31] = "25857";

Col0[32] = "Texas";
Col1[32] = "25809";

Col0[33] = "Arizona";
Col1[33] = "25571";

Col0[34] = "South Dakota";
Col1[34] = "25570";

Col0[35] = "Michigan";
Col1[35] = "25547";

Col0[36] = "Missouri";
Col1[36] = "25546";

Col0[37] = "Georgia";
Col1[37] = "25309";

Col0[38] = "North Carolina";
Col1[38] = "25285";

Col0[39] = "Montana";
Col1[39] = "25002";

Col0[40] = "Indiana";
Col1[40] = "24558";

Col0[41] = "Tennessee";
Col1[41] = "24294";

Col0[42] = "Louisiana";
Col1[42] = "24264";

Col0[43] = "Oklahoma";
Col1[43] = "24046";

Col0[44] = "South Carolina";
Col1[44] = "23906";

Col0[45] = "Utah";
Col1[45] = "23794";

Col0[46] = "New Mexico";
Col1[46] = "23749";

Col0[47] = "Alabama";
Col1[47] = "23587";

Col0[48] = "Kentucky";
Col1[48] = "23210";

Col0[49] = "Idaho";
Col1[49] = "22581";

Col0[50] = "West Virginia";
Col1[50] = "22482";

Col0[51] = "Arkansas";
Col1[51] = "22007";

Col0[52] = "Mississippi";
Col1[52] = "20670";


